public with sharing class Portal_Profile {
    public user userobj1 { get; set; }
    public User userobj{get; set;}
    public string firstname{get; set;}
    public string lastname{get; set;}
    public string phone{get; set;}
    public string email{get; set;}
    public contact user1{get; set;}
    public string addname{get;set;}
    public string address{get; set;}
    public string landmark{get; set;}
    public string City{get;set;}
    public string zip{get;set;}
    public string phonenumber{get;set;}
    public string state{get; set;}
    public Addreess__c add_update{get; set;}
    public string country{get; set;}
    public Portal_globalClass globalObj{get;set;}
    
    public Portal_Profile(){
     
     
    }   


        
    }